[tool.poetry]
name = "clattr"
version = "0.0.0"
description = "Construct a comand line interface based on a function or class"
authors = ["Tom Dimiduk <tom@dimiduk.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6"
attrs = "^20.3.0"

[tool.poetry.dev-dependencies]
black = "^21.4b2"
isort = "^5.8.0"
mypy = "^0.812"
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
